### ISSUE TITLE
Application always run in production mode

### ISSUE THREAD

**Issue by ghost** [Fingertips/passengerpane#30] opened 2009-12-17 15:02 UTC
I have a Radiant application that always is run in production mode.  I've selected the Run in: Development option, which generates the following vhost.conf file:

<VirtualHost *:80>
  ServerName radiant-test.local
  ServerAlias radiant.local
  DocumentRoot "/Users/user_name/src/test/radiant_test/public"
  RackEnv development
  <Directory "/Users/user_name/src/test/radiant_test/public">
    Order allow,deny
    Allow from all
  </Directory>
</VirtualHost>

However, the application is nonetheless run in production mode.  The output is going to the production.log and the production database is receiving all the editing changes.

This is a new install of Passenger (gem install, version 2.2.8) with the 1.3 version of PassengerPane having followed the instructions at http://wiki.github.com/radiant/radiant/installing-on-mac-os.

Researching this issue, I saw a closed defect (#24) that seemed similar.  One notes that Radiant has a config/environment.rb file, but uses a Radiant::Initializer block, not a Rails::Initializer block.  Also, manually changing RackEnv to RailsEnv or just adding a "RailsEnv development" line to the vhost.conf file did not change the behavior.

**Comment by alloy** [comment] 2010-01-13 10:15
Sorry for the delayed response, I didn't receive any notification emails.

Were you able to find the cause of the problem since then? (It doesn't sound as if this is an issue of the pane, since you already tried changing the env key and value manually.)

**Comment by njvack** [comment] 2010-06-08 17:28
For me, passenger writes:
RackEnv development

to the vhost file, but not
RailsEnv development

Adding the RailsEnv line and restarting apache did change the environment for me.

**Comment by alloy** [comment] 2010-06-11 16:22
Recognize Rails apps like those produced by Radiant. Closed by afcfb140f7a5e38c5fca3e9e0e4925d7274e2f77.

**Closed as completed** 2010-06-11 23:22 UTC

**Comment by peterz** [comment] 2010-08-30 15:49
I also have to manually add RailsEnv in vhost file. Any known reasons why pane don't write it when choosing env mode?
